import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
          name: 'Tejas',
          email:"admin@example.com",
          password: bcrypt.hashSync("1234", 8),
          isAdmin: true,
        },
        {
          name: 'yusuf',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],

    products: [
        {
            name:'Peter England Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Peter England',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            name:'Nike Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 80,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            name:'Van Huesen Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 70,
            countInStock: 0,
            brand: 'Van Huesen',
            rating: 4.8,
            numReviews: 17,
            description: 'High quality product',
        },
        {
            name:'Peter England Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 140,
            countInStock: 15,
            brand: 'Peter England',
            rating: 4.5,
            numReviews: 16,
            description: 'High quality product',
        },
        {
            name:'Nike Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 110,
            countInStock: 55,
            brand: 'Nike',
            rating: 4.0,
            numReviews: 18,
            description: 'High quality product',
        },
        {
            name:'Van Huesen Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 65,
            countInStock: 14,
            brand: 'Van Huesen',
            rating: 4.7,
            numReviews: 15,
            description: 'High quality product',
        },
    ],
};
export default data;